In [2]:
import leafmap

In [3]:
m = leafmap.Map()
m

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

In [4]:
m = leafmap.Map(center=(40, -100), zoom=4, height="600px")
m

Map(center=[40, -100], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_t…

In [5]:
m = leafmap.Map(
    center=(40, -100),
    zoom=4,
    zoom_control=False,
    draw_control=False,
    scale_control=False,
    fullscreen_control=False,
    attribution_control=False,
    toolbar_control=False,
)
m

Map(center=[40, -100], crs={'name': 'EPSG3857', 'custom': False}, default_style=MapStyle(), dragging_style=Map…

In [6]:
m = leafmap.Map(center=(40, -100), zoom=4, draw_control=False, height="500px")
url = "https://nominatim.openstreetmap.org/search?format=json&q={s}"
m.add_search_control(url=url, zoom=10, position="topleft")
m

Map(center=[40, -100], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_t…

In [7]:
m = leafmap.Map()
print(f"Number of layers: {len(m.layers)}")
print(f"Layer types: {[type(layer).__name__ for layer in m.layers]}")

Number of layers: 1
Layer types: ['TileLayer']

In [8]:
if len(m.layers) > 1: # keeps at least one layer
    m.remove_layer(m.layers[-1])

In [9]:
m.clear_controls()
m.clear_layers()
m

Map(center=[20, 0], crs={'name': 'EPSG3857', 'custom': False}, default_style=MapStyle(), dragging_style=MapSty…

In [10]:
m = leafmap.Map()
m.add_basemap("OpenTopoMap")
# m.add_basemap_gui() if you want to add the GUI and choose many
m

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

In [11]:
m = leafmap.Map()
m.add_tile_layer(
    url="https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}",
    name="Google Satellite",
    attribution="Google",
)
m

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

In [12]:
m = leafmap.Map(center=[33.4484,-112.0740], zoom=10)
url = "https://imagery.nationalmap.gov/arcgis/services/USGSNAIPPlus/ImageServer/WMSServer?"
m.add_wms_layer(
    url=url,
    layers="USGSNAIPPlus:FalseColorComposite",
    name="NAIP False Color Composite",
    attribution="USGS",
    format="image/png",
    shown=True
)
m.add_tile_layer(
    url="https://mt1.google.com/vt/lyrs=h&x={x}&y={y}&z={z}",
    name="Google Labels and Roads",
    attribution="Google",
)
m

Map(center=[33.4484, -112.074], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'z…

In [13]:
m = leafmap.Map(center=[33.4484,-112.0740], zoom=10)
m.add_basemap("Esri.WorldImagery")
url = "https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2021_Land_Cover_L48/wms?"
m.add_wms_layer(
    url=url,
    layers="NLCD_2021_Land_Cover_L48",
    name="NLCD 2021 Land Cover",
    attribution="MRLC",
    format="image/png",
    shown=True
)
m.add_legend(title="NLCD 2021 Land Cover Type", builtin_legend="NLCD", position="bottomleft")
m

Map(center=[33.4484, -112.074], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'z…

In [14]:
m = leafmap.Map(center=[33.4484, -112.0740], zoom=12)
#Syntax: [latitude, longitude]
locations = [
    [33.4216, -111.9388], # Coor Hall
    [33.4453, -112.0667], # Chase Field
    [33.4352, -112.0060], # Phoenix Sky Harbor Airport
    [33.5154, -111.9610] # Camelback Mountain Summit
]
m.add_markers(locations, draggable=True)
m

Map(center=[33.4484, -112.074], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'z…

In [15]:
m = leafmap.Map()
url = "https://github.com/opengeos/datasets/releases/download/world/world_cities.csv"
m.add_marker_cluster(url, x="longitude", y="latitude", layer_name="World Cities")
m

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

In [ ]:
m = leafmap.Map(center=[40, -100], zoom=4)
cities = "https://github.com/opengeos/datasets/releases/download/us/cities.csv"
regions = "https://github.com/opengeos/datasets/releases/download/us/us_regions.geojson"
m.add_geojson(regions, layer_name="US Regions")
m.add_points_from_xy(
    cities,
    x="longitude",
    y="latitude",
    color_column="region",
    icon_names=["gear","map","leaf","globe"],
    spin=True,
    add_legend=True
)
m

Map(center=[40, -100], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_t…

In [18]:
import geopandas as gpd

data = "https://github.com/opengeos/datasets/releases/download/vector/cables.geojson"
gdf = gpd.read_file(data)
gdf.head()

,id,name,color,feature_id,geometry
0,taiwan-penghu-kinmen-matsu-no-3-tpkm3,Taiwan Penghu Kinmen Matsu No.3 (TPKM3),#4dbd9a,taiwan-penghu-kinmen-matsu-no-3-tpkm3-0,"MULTILINESTRING ((119.93948 26.15145, 120.2624..."
1,unitirreno-cable,Unitirreno Cable,#939597,unitirreno-cable-0,"MULTILINESTRING ((10.91257 41.06934, 11.70007 ..."
2,kochi-lakshadweep-islands-cable,Kochi-Lakshadweep Islands Cable,#939597,kochi-lakshadweep-islands-cable-0,"MULTILINESTRING ((73.64411 10.06982, 73.91252 ..."
3,sagres,Sagres,#4ab970,sagres-0,"MULTILINESTRING ((-9.10275 38.44308, -8.99992 ..."
4,continente-madeira,Continente-Madeira,#37b98e,continente-madeira-0,"MULTILINESTRING ((-9.33156 38.69016, -10.79992..."

In [19]:
m = leafmap.Map(center=[20,0],zoom=2)
m.add_basemap("CartoDB.DarkMatter")
data = "https://github.com/opengeos/datasets/releases/download/vector/cables.geojson"
callback = lambda feat: {"color": feat["properties"]["color"], "weight": 2}
m.add_vector(data, layer_name="Cable Lines", info_mode="on_hover", style_callback=callback)
m

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

In [21]:
url = "https://gis.m.asu.edu/server/rest/services/Campus/CampusBuilding/MapServer/0/query?where=1%3D1&outFields=*&f=geojson"
gdf = leafmap.read_vector(url)
m = leafmap.Map(center=[33.4215, -111.9388], zoom=15)
m.add_basemap("Esri.WorldImagery")
style = {"color": "#8C1D40", "fullColor": "#FFC627", "fillOpacity": 0.4, "weight": 2}
m.add_gdf(gdf, style=style, layer_name="ASU Buildings")
m

Map(center=[33.4215, -111.9388], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', '…

In [23]:
m = leafmap.Map()
data = "https://raw.githubusercontent.com/opengeos/leafmap/master/docs/data/countries.geojson"
m.add_data(
    data, column="POP_EST", scheme="Quantiles", cmap="Blues", legend_title="Population"
)
m

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

In [26]:
leafmap.maxar_collections()

['BayofBengal-Cyclone-Mocha-May-23',
 'Belize-Wildfires-June24',
 'Brazil-Flooding-May24',
 'Cyclone-Chido-Dec15',
 'Cyclone-Ditwah-Sri-Lanka-Nov-2025',
 'Cyclone-Senyar-Indonesia-Nov-2025',
 'Cyclone-Senyar-Thailand-Nov-2025',
 'Earthquake-Myanmar-March-2025',
 'Emilia-Romagna-Italy-flooding-may23',
 'Floods-Spain-Oct24',
 'Gambia-flooding-8-11-2022',
 'Hurricane-Fiona-9-19-2022',
 'Hurricane-Ian-9-26-2022',
 'Hurricane-Idalia-Florida-Aug23',
 'Hurricane-Maria-PuertoRico-Oct-2017',
 'Hurricane-Melissa-Oct-2025',
 'HurricaneHelene-Oct24',
 'HurricaneMilton-Oct24',
 'Iceland-Volcano_Eruption-Dec-2023',
 'India-Floods-Oct-2023',
 'Indonesia-Earthquake22',
 'Japan-Earthquake-Jan-2024',
 'Kahramanmaras-turkey-earthquake-23',
 'Kalehe-DRC-Flooding-5-8-23',
 'Kenya-Flooding-May24',
 'Libya-Floods-Sept-2023',
 'Marshall-Fire-21-Update',
 'Maui-Hawaii-fires-Aug-23',
 'McDougallCreekWildfire-BC-Canada-Aug-23',
 'Morocco-Earthquake-Sept-2023',
 'Morocco-Flooding-Dec-2025',
 'NWT-Canada-Aug-23',
 'Nepal-Earthquake-Apr-2015',
 'Nepal-Earthquake-Nov-2023',
 'Nepal-Floods-Sept-2024',
 'New-Zealand-Flooding23',
 'Nigeria-Flooding-May-2025',
 'Nigeria-Floods-Sept-2024',
 'PNG-Landslide-June24',
 'SmokeHouseCreek-Wildfires-Texas-Mar24',
 'Sudan-flooding-8-22-2022',
 'Texas-Flooding-July-2025',
 'Typhoon-Kalmaegi-Nov-2025',
 'Vanuatu-Earthquake-Dec17',
 'WildFires-LosAngeles-Jan-2025',
 'afghanistan-earthquake22',
 'cyclone-emnati22',
 'ghana-explosion22',
 'kentucky-flooding-7-29-2022',
 'pakistan-flooding22',
 'shovi-georgia-landslide-8Aug23',
 'southafrica-flooding22',
 'tonga-volcano21',
 'volcano-indonesia21',
 'yellowstone-flooding22']

In [50]:
collection = "Kahramanmaras-turkey-earthquake-23"
url = leafmap.maxar_collection_url(collection, dtype="geojson")
url

'https://raw.githubusercontent.com/giswqs/maxar-open-data/master/datasets/Kahramanmaras-turkey-earthquake-23.geojson'

In [51]:
gdf = leafmap.read_vector(url)
print(f"Total number of images: {len(gdf)}")
gdf.head(100)

Total number of images: 2115

,datetime,platform,gsd,ard_metadata_version,catalog_id,utm_zone,quadkey,view:off_nadir,view:azimuth,view:incidence_angle,...,grid:code,proj:bbox,tile:data_area,tile:clouds_area,tile:clouds_percent,visual,ms_analytic,pan_analytic,data-mask,geometry
0,2021-02-28 08:10:22+00:00,WV03,0.39,0.0.1,1040010067C49900,37,120020230322,29.4,22.0,57.4,...,MXRA-Z37-120020230322,"600452.7792440292,4199843.75,605156.25,4204327...",20.8,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((40.19672 37.94010, 40.14382 37.94062..."
1,2021-02-28 08:10:22+00:00,WV03,0.39,0.0.1,1040010067C49900,37,120020230323,29.3,21.3,57.6,...,MXRA-Z37-120020230323,"604843.75,4199843.75,610156.25,4204393.030737486",23.9,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((40.25361 37.93950, 40.19317 37.94013..."
2,2021-02-28 08:10:22+00:00,WV03,0.39,0.0.1,1040010067C49900,37,120020230332,29.1,20.6,57.8,...,MXRA-Z37-120020230332,"609843.75,4199843.75,615155.9736693815,4204458...",24.1,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((40.25006 37.93954, 40.25075 37.98047..."
3,2021-02-28 08:10:22+00:00,WV03,0.39,0.0.1,1040010067C49900,37,120020230333,29.1,20.3,57.8,...,MXRA-Z37-120020230333,"614843.75,4199843.75,615155.9736693815,4204458...",1.2,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((40.30694 37.93892, 40.30768 37.98047..."
4,2021-02-28 08:10:23+00:00,WV03,0.39,0.0.1,1040010067C49900,37,120020232100,29.4,21.8,57.4,...,MXRA-Z37-120020232100,"600503.194703785,4194843.75,605156.25,4200156.25",24.5,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((40.19677 37.94291, 40.19599 37.89504..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-07-20 08:39:38+00:00,WV02,0.55,0.0.1,10300100D6789800,37,031133023300,24.2,344.5,62.6,...,MXRA-Z37-031133023300,"243262.48583240228,4017609.184957668,244262.16...",0.4,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.14573 36.27003, 36.14350 36.27026..."
96,2022-07-20 08:39:38+00:00,WV02,0.55,0.0.1,10300100D6789800,37,031133023301,24.3,343.9,62.5,...,MXRA-Z37-031133023301,"245691.62782046685,4017126.19149604,250156.25,...",10.3,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.18047 36.26760, 36.16934 36.26852..."
97,2022-07-20 08:39:38+00:00,WV02,0.55,0.0.1,10300100D6789800,37,031133023310,24.4,343.2,62.4,...,MXRA-Z37-031133023310,"249843.75,4018216.2791011026,251621.7053677838...",2.4,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.21438 36.29397, 36.22596 36.29424..."
98,2022-07-26 08:19:46+00:00,WV02,0.54,0.0.1,10300100D797E100,37,031131233232,23.2,143.9,63.7,...,MXRA-Z37-031131233232,"314738.45123535924,4159843.75,315156.25,416316...",1.2,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.90702 37.56709, 36.90229 37.56701..."
99,2022-07-26 08:19:46+00:00,WV02,0.54,0.0.1,10300100D797E100,37,031131233233,23.1,144.6,63.9,...,MXRA-Z37-031131233233,"314843.75,4159843.75,319758.3041869086,4163163...",15.9,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.90348 37.56703, 36.90264 37.59693..."

In [52]:
m = leafmap.Map()
m.add_basemap("Esri.WorldImagery")
m.add_gdf(gdf, layer_name="Footprints", zoom_to_layer=True)
m

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

In [60]:
pre_gdf = leafmap.maxar_search(collection, end_date="2023-02-06")
print(f"Total number of pre-event images: {len(pre_gdf)}")
pre_gdf.head()

Total number of pre-event images: 229

,datetime,platform,gsd,ard_metadata_version,catalog_id,utm_zone,quadkey,view:off_nadir,view:azimuth,view:incidence_angle,...,grid:code,proj:bbox,tile:data_area,tile:clouds_area,tile:clouds_percent,visual,ms_analytic,pan_analytic,data-mask,geometry
0,2021-02-28 08:10:22+00:00,WV03,0.39,0.0.1,1040010067C49900,37,120020230322,29.4,22.0,57.4,...,MXRA-Z37-120020230322,"600452.7792440292,4199843.75,605156.25,4204327...",20.8,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((40.19672 37.94010, 40.14382 37.94062..."
1,2021-02-28 08:10:22+00:00,WV03,0.39,0.0.1,1040010067C49900,37,120020230323,29.3,21.3,57.6,...,MXRA-Z37-120020230323,"604843.75,4199843.75,610156.25,4204393.030737486",23.9,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((40.25361 37.93950, 40.19317 37.94013..."
2,2021-02-28 08:10:22+00:00,WV03,0.39,0.0.1,1040010067C49900,37,120020230332,29.1,20.6,57.8,...,MXRA-Z37-120020230332,"609843.75,4199843.75,615155.9736693815,4204458...",24.1,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((40.25006 37.93954, 40.25075 37.98047..."
3,2021-02-28 08:10:22+00:00,WV03,0.39,0.0.1,1040010067C49900,37,120020230333,29.1,20.3,57.8,...,MXRA-Z37-120020230333,"614843.75,4199843.75,615155.9736693815,4204458...",1.2,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((40.30694 37.93892, 40.30768 37.98047..."
4,2021-02-28 08:10:23+00:00,WV03,0.39,0.0.1,1040010067C49900,37,120020232100,29.4,21.8,57.4,...,MXRA-Z37-120020232100,"600503.194703785,4194843.75,605156.25,4200156.25",24.5,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((40.19677 37.94291, 40.19599 37.89504..."

In [61]:
post_gdf = leafmap.maxar_search(collection, start_date="2023-02-06")
print(f"Total number of post-event images: {len(post_gdf)}")
post_gdf.head()

Total number of post-event images: 1886

,datetime,platform,gsd,ard_metadata_version,catalog_id,utm_zone,quadkey,view:off_nadir,view:azimuth,view:incidence_angle,...,grid:code,proj:bbox,tile:data_area,tile:clouds_area,tile:clouds_percent,visual,ms_analytic,pan_analytic,data-mask,geometry
229,2023-02-07 08:27:01+00:00,WV03,0.31,0.0.1,1040010082698700,37,031133010300,5.7,180.5,83.8,...,MXRA-Z37-031133010300,"284307.55615234375,4134843.75,285156.25,413773...",2.3,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.56529 37.36127, 36.57405 37.36116..."
230,2023-02-07 08:27:01+00:00,WV03,0.31,0.0.1,1040010082698700,37,031133010301,5.7,181.3,83.8,...,MXRA-Z37-031133010301,"284843.75,4134843.75,290156.25,4137711.7919921875",14.8,0.1,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.57052 37.36120, 36.57135 37.33537..."
231,2023-02-07 08:27:01+00:00,WV03,0.31,0.0.1,1040010082698700,37,031133010310,5.7,186.0,83.7,...,MXRA-Z37-031133010310,"289843.75,4134843.75,295156.25,4137567.7490234375",14.2,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.62697 37.36105, 36.62774 37.33652..."
232,2023-02-07 08:27:01+00:00,WV03,0.31,0.0.1,1040010082698700,37,031133010311,5.8,188.8,83.7,...,MXRA-Z37-031133010311,"294843.75,4134843.75,297504.8828125,4137500.61...",6.9,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.68693 37.36163, 36.69621 37.36150..."
233,2023-02-07 08:27:02+00:00,WV03,0.31,0.0.1,1040010082698700,37,031133010302,5.7,180.6,83.7,...,MXRA-Z37-031133010302,"284180.908203125,4129843.75,285156.25,4135156.25",4.8,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.56530 37.33806, 36.57478 37.33826..."

In [62]:
m = leafmap.Map()
m.add_basemap("Esri.WorldImagery")
pre_style = {"color": "red", "fillColor": "red", "opacity": 1, "fillOpacity": 0.5}
m.add_gdf(
    pre_gdf,
    layer_name="Pre-Event",
    style=pre_style,
    info_mode="on_click",
    zoom_to_layer=True
)
m.add_gdf(post_gdf, layer_name="Post-Event", info_mode="on_click", zoom_to_layer=True)
m

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

In [66]:
bbox = m.user_roi_bounds()
if bbox is None:
    bbox = [36.8715, 37.5497, 36.9814, 37.6019]

In [73]:
print(f"Bounding box: {bbox}")

Bounding box: [36.8715, 37.5497, 36.9814, 37.6019]

In [79]:
import geopandas as gpd

# union_all() was added in GeoPandas 1.0; patch for older versions
if not hasattr(gpd.GeoDataFrame, 'union_all'):
    gpd.GeoDataFrame.union_all = lambda self, **kwargs: self.geometry.unary_union

In [80]:
pre_event = leafmap.maxar_search(collection, bbox=bbox, end_date="2023-02-06")
pre_event

,datetime,platform,gsd,ard_metadata_version,catalog_id,utm_zone,quadkey,view:off_nadir,view:azimuth,view:incidence_angle,...,grid:code,proj:bbox,tile:data_area,tile:clouds_area,tile:clouds_percent,visual,ms_analytic,pan_analytic,data-mask,geometry
98,2022-07-26 08:19:46+00:00,WV02,0.54,0.0.1,10300100D797E100,37,031131233232,23.2,143.9,63.7,...,MXRA-Z37-031131233232,"314738.45123535924,4159843.75,315156.25,416316...",1.2,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.90702 37.56709, 36.90229 37.56701..."
99,2022-07-26 08:19:46+00:00,WV02,0.54,0.0.1,10300100D797E100,37,031131233233,23.1,144.6,63.9,...,MXRA-Z37-031131233233,"314843.75,4159843.75,319758.3041869086,4163163...",15.9,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.90348 37.56703, 36.90264 37.59693..."
100,2022-07-26 08:19:46+00:00,WV02,0.54,0.0.1,10300100D797E100,37,031133011010,23.1,143.8,63.9,...,MXRA-Z37-031133011010,"314714.4264589311,4158758.460866644,315156.25,...",0.5,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.90694 37.56991, 36.90729 37.55732..."
101,2022-07-26 08:19:46+00:00,WV02,0.54,0.0.1,10300100D797E100,37,031133011011,22.9,144.5,64.1,...,MXRA-Z37-031133011011,"314843.75,4158659.1890106304,319695.2811615013...",6.9,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.90340 37.56984, 36.95831 37.57081..."

In [81]:
post_event = leafmap.maxar_search(collection, bbox=bbox, start_date="2023-02-06")
post_event.head()

,datetime,platform,gsd,ard_metadata_version,catalog_id,utm_zone,quadkey,view:off_nadir,view:azimuth,view:incidence_angle,...,grid:code,proj:bbox,tile:data_area,tile:clouds_area,tile:clouds_percent,visual,ms_analytic,pan_analytic,data-mask,geometry
435,2023-02-08 09:02:04+00:00,WV02,0.78,0.0.1,10300500D9F8D200,37,031131233232,40.2,273.1,43.6,...,MXRA-Z37-031131233232,"309843.75,4159843.75,315156.25,4165156.25",28.2,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.84552 37.61386, 36.84690 37.56601..."
436,2023-02-08 09:02:04+00:00,WV02,0.79,0.0.1,10300500D9F8D200,37,031131233233,40.4,273.1,43.4,...,MXRA-Z37-031131233233,"314843.75,4159843.75,320156.25,4165156.25",28.2,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.90214 37.61488, 36.90348 37.56703..."
439,2023-02-08 09:02:04+00:00,WV02,0.79,0.0.1,10300500D9F8D200,37,031131233322,40.6,273.1,43.1,...,MXRA-Z37-031131233322,"319843.75,4159843.75,325156.25,4165156.25",28.2,0.0,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.95876 37.61588, 36.96006 37.56802..."
446,2023-02-08 09:02:04+00:00,WV02,0.78,0.0.1,10300500D9F8D200,37,031133011010,40.3,273.3,43.6,...,MXRA-Z37-031133011010,"309843.75,4154843.75,315156.25,4160156.25",28.2,0.5,1,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.84682 37.56883, 36.84820 37.52098..."
447,2023-02-08 09:02:04+00:00,WV02,0.79,0.0.1,10300500D9F8D200,37,031133011011,40.5,273.3,43.3,...,MXRA-Z37-031133011011,"314843.75,4154843.75,320156.25,4160156.25",28.2,0.1,0,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,https://maxar-opendata.s3.amazonaws.com/events...,"POLYGON ((36.90340 37.56984, 36.90474 37.52199..."

In [82]:
pre_tile = pre_event["catalog_id"].values[0]
pre_tile

'10300100D797E100'

In [83]:
post_tile=post_event["catalog_id"].values[0]
post_tile

'10300500D9F8D200'

In [84]:
pre_stac = leafmap.maxar_tile_url(collection, pre_tile, dtype="json")
post_stac = leafmap.maxar_tile_url(collection, post_tile, dtype="json")

In [85]:
m = leafmap.Map()
m.split_map(
    left_layer=pre_stac,
    right_layer=post_stac,
    left_label="Pre-Event",
    right_label="Post-Event",
)
m.set_center(36.9265, 37.5762, 16)
m

Map(center=[37.5762, 36.9265], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zo…

In [86]:
pre_images = pre_event["visual"].tolist()
post_images = post_event["visual"].tolist()

In [87]:
leafmap.maxar_download(pre_images)
leafmap.maxar_download(post_images)

Downloading 1 out of 4: 10300100D797E100/031131233232.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233232/2022-07-26/10300100D797E100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100D797E100\031131233232.tif
100%|██████████| 7.01M/7.01M [00:04<00:00, 1.61MB/s]

Downloading 2 out of 4: 10300100D797E100/031131233233.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233233/2022-07-26/10300100D797E100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100D797E100\031131233233.tif
100%|██████████| 52.3M/52.3M [00:16<00:00, 3.14MB/s]

Downloading 3 out of 4: 10300100D797E100/031133011010.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011010/2022-07-26/10300100D797E100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100D797E100\031133011010.tif
100%|██████████| 4.16M/4.16M [00:01<00:00, 2.10MB/s]

Downloading 4 out of 4: 10300100D797E100/031133011011.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011011/2022-07-26/10300100D797E100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100D797E100\031133011011.tif
100%|██████████| 20.4M/20.4M [00:08<00:00, 2.46MB/s]

Downloading 01 out of 24: 10300500D9F8D200/031131233232.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233232/2023-02-08/10300500D9F8D200-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300500D9F8D200\031131233232.tif
100%|██████████| 72.3M/72.3M [00:21<00:00, 3.35MB/s]

Downloading 02 out of 24: 10300500D9F8D200/031131233233.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233233/2023-02-08/10300500D9F8D200-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300500D9F8D200\031131233233.tif
100%|██████████| 77.3M/77.3M [00:06<00:00, 12.7MB/s]

Downloading 03 out of 24: 10300500D9F8D200/031131233322.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233322/2023-02-08/10300500D9F8D200-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300500D9F8D200\031131233322.tif
100%|██████████| 62.1M/62.1M [00:06<00:00, 10.0MB/s]

Downloading 04 out of 24: 10300500D9F8D200/031133011010.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011010/2023-02-08/10300500D9F8D200-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300500D9F8D200\031133011010.tif
100%|██████████| 51.9M/51.9M [00:09<00:00, 5.30MB/s]

Downloading 05 out of 24: 10300500D9F8D200/031133011011.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011011/2023-02-08/10300500D9F8D200-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300500D9F8D200\031133011011.tif
100%|██████████| 57.1M/57.1M [00:07<00:00, 7.83MB/s]

Downloading 06 out of 24: 10300500D9F8D200/031133011100.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011100/2023-02-08/10300500D9F8D200-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300500D9F8D200\031133011100.tif
100%|██████████| 52.3M/52.3M [00:05<00:00, 8.89MB/s]

Downloading 07 out of 24: 10300100E19A4400/031133011010.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011010/2023-02-11/10300100E19A4400-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E19A4400\031133011010.tif
100%|██████████| 53.0M/53.0M [00:05<00:00, 10.4MB/s]

Downloading 08 out of 24: 10300100E19A4400/031131233232.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233232/2023-02-11/10300100E19A4400-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E19A4400\031131233232.tif
100%|██████████| 77.6M/77.6M [00:07<00:00, 10.2MB/s]

Downloading 09 out of 24: 10300100E19A4400/031131233233.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233233/2023-02-11/10300100E19A4400-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E19A4400\031131233233.tif
100%|██████████| 51.0M/51.0M [00:04<00:00, 10.3MB/s]

Downloading 10 out of 24: 10300100E19A4400/031133011011.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011011/2023-02-11/10300100E19A4400-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E19A4400\031133011011.tif
100%|██████████| 37.2M/37.2M [00:06<00:00, 5.54MB/s]

Downloading 11 out of 24: 10300100E291D100/031131233233.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233233/2023-02-11/10300100E291D100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E291D100\031131233233.tif
100%|██████████| 71.2M/71.2M [00:16<00:00, 4.35MB/s]

Downloading 12 out of 24: 10300100E291D100/031131233322.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233322/2023-02-11/10300100E291D100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E291D100\031131233322.tif
100%|██████████| 76.4M/76.4M [00:05<00:00, 12.8MB/s]

Downloading 13 out of 24: 10300100E291D100/031133011011.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011011/2023-02-11/10300100E291D100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E291D100\031133011011.tif
100%|██████████| 52.7M/52.7M [00:03<00:00, 13.4MB/s]

Downloading 14 out of 24: 10300100E291D100/031133011100.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011100/2023-02-11/10300100E291D100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E291D100\031133011100.tif
100%|██████████| 62.3M/62.3M [00:08<00:00, 7.71MB/s]

Downloading 15 out of 24: 10300100E2C66F00/031131233232.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233232/2023-02-28/10300100E2C66F00-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E2C66F00\031131233232.tif
100%|██████████| 75.9M/75.9M [00:07<00:00, 9.68MB/s]

Downloading 16 out of 24: 10300100E2C66F00/031131233233.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233233/2023-02-28/10300100E2C66F00-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E2C66F00\031131233233.tif
100%|██████████| 12.5M/12.5M [00:01<00:00, 10.9MB/s]

Downloading 17 out of 24: 10300100E2C66F00/031133011010.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011010/2023-02-28/10300100E2C66F00-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E2C66F00\031133011010.tif
100%|██████████| 62.5M/62.5M [00:06<00:00, 9.58MB/s]

Downloading 18 out of 24: 10300100E2C66F00/031133011011.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011011/2023-02-28/10300100E2C66F00-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E2C66F00\031133011011.tif
100%|██████████| 9.94M/9.94M [00:01<00:00, 6.64MB/s]

Downloading 19 out of 24: 10300100E3154100/031133011010.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011010/2023-02-28/10300100E3154100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E3154100\031133011010.tif
100%|██████████| 25.0M/25.0M [00:02<00:00, 10.5MB/s]

Downloading 20 out of 24: 10300100E3154100/031133011011.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011011/2023-02-28/10300100E3154100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E3154100\031133011011.tif
100%|██████████| 59.6M/59.6M [00:06<00:00, 9.90MB/s]

Downloading 21 out of 24: 10300100E3154100/031133011100.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031133011100/2023-02-28/10300100E3154100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E3154100\031133011100.tif
100%|██████████| 53.3M/53.3M [00:05<00:00, 9.59MB/s]

Downloading 22 out of 24: 10300100E3154100/031131233232.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233232/2023-02-28/10300100E3154100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E3154100\031131233232.tif
100%|██████████| 31.7M/31.7M [00:02<00:00, 10.8MB/s]

Downloading 23 out of 24: 10300100E3154100/031131233233.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233233/2023-02-28/10300100E3154100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E3154100\031131233233.tif
100%|██████████| 77.4M/77.4M [00:46<00:00, 1.65MB/s]

Downloading 24 out of 24: 10300100E3154100/031131233322.tif

Downloading...
From: https://maxar-opendata.s3.amazonaws.com/events/Kahramanmaras-turkey-earthquake-23/ard/37/031131233322/2023-02-28/10300100E3154100-visual.tif
To: d:\DevSource\gis322\lecture6_advancedvisualization\10300100E3154100\031131233322.tif
100%|██████████| 66.7M/66.7M [00:45<00:00, 1.48MB/s]

In [88]:
import leafmap.maplibregl as leafmap

In [89]:
m = leafmap.Map(style="voyager", projection="globe")
m

Html(children=[Map(calls=[['addControl', ('NavigationControl', {'showCompass': True, 'showZoom': True, 'visual…